### ISSUE TITLE
Read error on wildfly

### ISSUE THREAD

**Issue by dpom** [weavejester/ragtime#136]
Hello,

In my web application I implemented a migrator component:
```clojure
(ns migrator
  (:require
   [ragtime.jdbc :as jdbc]
   [ragtime.core :as ragtime]
    ...)
(defprotocol Migrate
  (migrate [this] "migrate to the last migration")
  (rollback [this migration-id] "return to the ID migration"))

(defrecord JdbcMigrator [store datastore migrations index strategy reporter logger]
  Migrate
  (migrate [this]
    (ragtime/migrate-all datastore index migrations {:strategy (get-strategy strategy) :reporter reporter}))
  (rollback [this migration-id]
    (ragtime/rollback-to datastore index migration-id)))

(defmethod ig/init-key ig-key
  [_ {:keys [logger store strategy migrations]}]
  (let [datastore (jdbc/sql-database (:dbspec store))
        migrs     (jdbc/load-resources migrations)
        index     (ragtime/into-index migrs)
        reporter  (if logger
                    (logger-reporter logger)
                    reporter/print)
        migrator  (->JdbcMigrator store datastore migrs index strategy reporter logger)]
    (migrate migrator)
    migrator))
```
The migrations are sql files in resources/migrations folder.
The application works ok in repl and tests but when deployed to wildfly 8.2.0 Final failed with the message:
```clojure
Caused by: java.lang.IllegalArgumentException: No method in multimethod 'url-dir' for dispatch value: vfs
    at clojure.lang.MultiFn.getFn(MultiFn.java:156)
    at clojure.lang.MultiFn.invoke(MultiFn.java:229)
    at clojure.core$map$fn__5587.invoke(core.clj:2747)
    at clojure.lang.LazySeq.sval(LazySeq.java:40)
    at clojure.lang.LazySeq.seq(LazySeq.java:49)
    at clojure.lang.RT.seq(RT.java:528)
    at clojure.core$seq__5124.invokeStatic(core.clj:137)
    at clojure.core$apply.invokeStatic(core.clj:652)
    at clojure.core$mapcat.invokeStatic(core.clj:2775)
    at clojure.core$mapcat.doInvoke(core.clj:2775)
    at clojure.lang.RestFn.invoke(RestFn.java:423)
    at resauce.core$resource_dir.invokeStatic(core.clj:72)
    at resauce.core$resource_dir.invoke(core.clj:68)
    at resauce.core$resource_dir.invokeStatic(core.clj:71)
    at resauce.core$resource_dir.invoke(core.clj:68)
    at ragtime.jdbc$load_resources.invokeStatic(jdbc.clj:155)
    at ragtime.jdbc$load_resources.invoke(jdbc.clj:152)
  ```
I made some research and it seems there is a bug in wildfly and immutant. To solve this I started to implement a new load-resources function which check the protocol (file, jar or vfs).
Is there a simpler method?

**Comment by weavejester** [comment]
Yes, you just need to write a method for `resauce.core/url-dir` for `"vfs"`. This should take a URL denoting a directory (or the equivalent thereof) and return a list of URLs to resources in the directory.

**Comment by dpom** [comment]
Thank for your suggestion. I add methods for resauce.core/directory? and resauce.core/url-dir for "vfs" and  ragtime.jdbc/load-resources works with vfs sql files.
