### ISSUE TITLE
But migrating 0.5.0

### ISSUE THREAD

**Issue by donbonifacio** [weavejester/ragtime#79]
Hello, just tried `0.5.0` from `0.4.2`and got the following exception. I'm using SQL files.

```
Exception in thread "main" java.lang.IllegalArgumentException: No implementation of method: :applied-migration-ids of protocol: #'ragtime.protocols/DataStore found for class: nil, compiling:(/tmp/form-init8004482708322009980.clj:1:73)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No implementation of method: :applied-migration-ids of protocol: #'ragtime.protocols/DataStore found for class: nil
	at clojure.core$_cache_protocol_fn.invoke(core_deftype.clj:554)
	at ragtime.protocols$eval542$fn__543$G__533__548.invoke(protocols.clj:12)
	at ragtime.core$applied_migrations.invoke(core.clj:16)
	at ragtime.core$migrate_all.invoke(core.clj:42)
	at ragtime.repl$migrate.invoke(repl.clj:49)
	at clanhr.absences_api.config.database$migrate.invoke(database.clj:10)
	at clojure.lang.Var.invoke(Var.java:375)
	at user$eval9.invoke(form-init8004482708322009980.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
```

**Comment by cassiomarques** [comment]
I had this problem during the weekend :smile: 

In your config map, you need to replace the `:database` keyword with `:datastore`.

**Comment by donbonifacio** [comment]
Hey @cassiomarques, that was it. Thanks :)

**Comment by weavejester** [comment]
Ah, sorry about that. I've added a wiki page and a link from the README to mention that change. https://github.com/weavejester/ragtime/wiki/Upgrading-from-0.4.x

**Comment by ryanbaldwin** [comment]
Oddly, I'm getting this while using the duct/ragtime-component (v0.1.2). Looking at my deps v0.5.1 of Ragtime is in there. My test component successfully migrates, but fails to rollback with the exact error as seen above.

I've been stumped for hours on this. Thoughts?

**Comment by ryanbaldwin** [comment]
Strike that - this appears to be something either I"m doing, or that Sierra's Component library is messing up while I try and sub a component during tests. My bad.
